version: 2

models:
  - name: fact_stocks
    description: "Fact table containing daily stock data for S&P 500 companies."
    columns:
      - name: symbol
  - name: dim_companies
    description: "Dimension table containing IDs, symbols, and names for S&P 500 companies."
    columns:
      - name: company_id
        description: "Unique identifier for the company."
      - name: company_symbol
        description: "A company's unique stock abbreviation."
      - name: company_name
        description: "A company's full name."
  - name: dim_industry
    description: "Dimension table containing industry ID and name for companies."
    columns:
      - name: industry_id
        description: "Unique identifier for the industry."
      - name: industry_name
        description: "Name of the industry."
  - name: dim_sector
    description: "Dimension table containing sector ID and name for companies."
    columns:
      - name: sector_id
        description: "Unique identifier for the sector."
      - name: sector_name
        description: "Name of the sector."
  - name: dim_states
    description: "Dimension table containing state ID and name for companies."
    columns:
      - name: state_id
        description: "Unique identifier for the state."
      - name: state_name
        description: "Name of the state."
  - name: dim_employees_count
    description: "Dimension table containing company ID and full-time employee count."
    columns:
      - name: company_id
        description: "Unique identifier for the company."
      - name: company_full_time_employees
        description: "Number of full-time employees in the company."
      - name: load_timestamp_utc_from
        description: "UTC timestamp indicating when the data was loaded from the source."
      - name: load_timestamp_utc_to
        description: "UTC timestamp indicating when the row of data is valid until."
