services:
  dbt:
    build:
      context: ..
      dockerfile: dbt/dbt.dockerfile
    volumes:
      - ../dbt/star:/usr/app/dbt/star
    entrypoint: [ "/bin/sh", "-c" ]
    command: [ "ls -ltr && dbt run && sleep infinity"]
    networks:
      - default_net
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_DEV_SCHEMA=${POSTGRES_DEV_SCHEMA}
      - POSTGRES_PROD_SCHEMA=${POSTGRES_PROD_SCHEMA}

networks:
  default_net:
    driver: bridge
