services:
  dbt:
    build:
      context: ..
      dockerfile: dbt/dbt.dockerfile
    volumes:
      - ../dbt/star:/usr/app/dbt/star
    entrypoint: [ "/bin/sh", "-c" ]
    command: [ "ls -ltr && dbt deps && dbt run && sleep infinity"]
    networks:
      - default_net

networks:
  default_net:
    driver: bridge
