services:
  dbt:
    build:
      context: ..
      dockerfile: dbt/dbt.dockerfile
    volumes:
      - ../dbt/star:/usr/app/dbt/star
    entrypoint: [ "/bin/sh", "-c" ]
    command: [ "sleep infinity"]
    networks:
      - default_net
    environment:
      - POSTGRES_SERVER=data-warehouse
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_DEV_SCHEMA=${POSTGRES_DEV_SCHEMA}
      - POSTGRES_PROD_SCHEMA=${POSTGRES_PROD_SCHEMA}
      - REDSHIFT_USER=${REDSHIFT_USER}
      - REDSHIFT_PASSWORD=${REDSHIFT_PASSWORD}
      - REDSHIFT_PORT=${REDSHIFT_PORT}
      - REDSHIFT_DB=${REDSHIFT_DB}
      - REDSHIFT_SERVER=${REDSHIFT_SERVER}
      - REDSHIFT_DEV_SCHEMA=${REDSHIFT_DEV_SCHEMA}
      - REDSHIFT_PROD_SCHEMA=${REDSHIFT_PROD_SCHEMA}

networks:
  default_net:
    external: true
    name: airflow_default_net 
