stock_transaction_streaming_profile:
  target: default
  outputs:
    default:
      type: redshift
      host: "{{ env_var('REDSHIFT_SERVER') }}"
      user: "{{ env_var('REDSHIFT_USER') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      port: "{{ env_var('REDSHIFT_PORT') }}"
      dbname: "{{ env_var('REDSHIFT_DB') }}"
      schema: "staging"
