services:
  transactions-producer:
    build:
      context: ..
      dockerfile: streaming/transactions_producer.dockerfile
    environment:
      AIRFLOW_PROJ_DIR: ${AIRFLOW_PROJ_DIR}
      PYTHONPATH: ${PYTHONPATH}
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags/:/opt/airflow/dags
    # entrypoint: [ "/bin/sh", "-c" ]
    entrypoint: [ "python", "../opt/airflow/apps/streaming/transactions_producer.py" ]
    command: [ "sleep infinity" ]
    networks:
      - default_net


networks:
  default_net:
    external: true
    name: airflow_default_net 
